/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AeriaButton: typeof import('@waltz-ui/ui')['AeriaButton']
    AeriaCard: typeof import('@waltz-ui/ui')['AeriaCard']
    AeriaIcon: typeof import('@waltz-ui/ui')['AeriaIcon']
    AeriaInput: typeof import('@waltz-ui/ui')['AeriaInput']
    AeriaPicture: typeof import('@waltz-ui/ui')['AeriaPicture']
    ClinicHead: typeof import('./src/components/clinic-head.vue')['default']
    MyButton: typeof import('./src/components/my-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
